-- Set Role and Create Warehouse
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DIGITAL_ASSET_ANALYTICS_PLATFORM_WH
  WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create and Use Database & Schema
CREATE OR REPLACE DATABASE DIGITAL_ASSET_ANALYTICS_PLATFORM_DB;
USE DATABASE DIGITAL_ASSET_ANALYTICS_PLATFORM_DB;
USE SCHEMA PUBLIC;