
CREATE OR REPLACE STORAGE INTEGRATION s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/s<ROLE_FOR_SNOWFLAKE>' 
  STORAGE_ALLOWED_LOCATIONS = ('s3://digital-asset-analytics-data-lake/');


DESC INTEGRATION s3_integration;

